### ISSUE TITLE
Flexible parameter injection

### ISSUE THREAD

**Issue by acuteaura** [mxriverlynn/mustbe#14]
In our current project we have _a lot_ of activities. We're currently looking into patching `paramsFromRequest` for our own version, so a parameter could be more easily injected into multiple activity handlers (i.e. check if the first argument of `ParameterMap.prototype.map` is an array of strings).

I'd just like to ask if you were willing to accept a PR for such a feature.

**Comment by DamonGant** [comment]
I put something functional together really fast, it's not super solid yet and I've added lodash out of habit, but it gets the point across.

**Comment by derickbailey** [comment]
thanks for the pull request @DamonGant! this is looking good, from a quick review of the code. i'll try to get this pulled in soon (hopefully today, but may be later this week)

**Comment by DamonGant** [comment]
Thanks @derickbailey, let me know when it's in so we can point our app back to npm :)

**Comment by sqrter** [comment]
Hi guys! Any updates on this feature?

**Comment by DamonGant** [comment]
Hi @sqrter,

you can simply full from my repository and merge the code in for now.
